library(reticulate)
library(keras)
library(tensorflow)
library(tidyverse)
library(fs)
library(tibble)
library(rsample)
library(tfdatasets)
library(unet)
library(EBImage)
library(platypus)
library(tiff)
library(png)
library(pixmap)
library(raster)
library(cellcount)
library(dplyr)
library(jjb)
library(shiny)
library(magick)
library(ggplot2)
library(shinyalert)
library(shinyFiles)
library(shinyjs)
library(shinyBS)
library(DT)
library(shinythemes)
library(cyanocount2.0)
#___________________________________________________________#
watershed_convert <- function(x, w = 17, h = 17, offset = 0.001, areathresh = 50, tolerance= 0.5, ext = 1, removeEdgeCells = TRUE) {
  if (removeEdgeCells == TRUE){
    image <- thresh(x, w = w, h = h, offset = offset)
    image1 <- fillHull(image)
    image2 <- watershed(distmap(image1), tolerance = tolerance, ext = ext)
    nf <- computeFeatures.shape(image2)
    nr <- which(nf[, "s.area"] < areathresh)
    image3 <- rmObjects(image2, nr)
    dims <- dim(image3)
    border1 <- c(image3[1:dims[1], 1], image3[1:dims[1], dims[2]], image3[1, 1:dims[2]], image3[dims[1], 1:dims[2]])
    ids <- unique(border1[which(border1 != 0)])
    inner <- rmObjects(image3, ids)
    return(inner)
  } else{
    image <- thresh(x, w = w, h = h, offset = offset)
    image1 <- fillHull(image)
    image2 <- watershed(distmap(image1), tolerance = tolerance, ext = ext)
    nf <- computeFeatures.shape(image2)
    nr <- which(nf[, "s.area"] < areathresh)
    image3 <- rmObjects(image2, nr)
    return(image3)
  }
}
#___________________________________________________________#

img_dir <- ("C:/Users/Tyler.Harman/Desktop/cellcount_work/CyanoSCOPE_imgs/AccuScope/Microcystis_F192/40X/Raw_Imgs/Batch_23")
images <- list.files(img_dir, pattern = "tif", full.name = T)
images_names <- list.files(img_dir, pattern = "tif", full.name = F)

imgNames <- paste0(images_names)
read_images <- lapply(images, readTIFF)
img_transposed <- lapply(read_images,aperm,c(1,2,3))

model<-load_model_tf('C:/Users/Tyler.Harman/Desktop/cellcount_work/CyanoSCOPE_imgs/AccuScope/Draft_Model/models/segmentation_model/initial_test_model/', custom_objects = NULL, compile = TRUE)

test_img<-image_load(images[[1]],target_size = c(256,256))
img_array<-test_img%>%image_to_array()%>%'/'(255)
rgb.imgs<-Image(img_array,colormode = Color)
new_array<-test_img%>%image_to_array()%>%array_reshape(.,c(1,dim(.)))%>%'/'(255)
mask_main<-model%>%predict(new_array)%>%
  get_masks(binary_colormap)
magick::image_ggplot(image_read(mask_main[[1]]/255))
mask<-abind(mask_main[[1]])
mask<-mask[,,1]
img_watershed<-watershed_convert(mask,w=50,h=50,offset=0.001,areathresh=50,tolerance=0.5,ext = 1,removeEdgeCells=TRUE)

ctmask<-opening(img_watershed>0.1,makeBrush(5,shape='disc'))
seed_mask<-single_cell_convert(ctmask)
cmask<-propagate(mask,seeds=seed_mask,mask=ctmask,lambda = 10^1)
cmask1<-array_reshape(cmask,c(dim(cmask),1))
display(rgb.imgs)
display(cmask1)
segmented<-paintObjects(cmask,rgb.imgs,col = c('black','orange'))
display(segmented,all=TRUE)
st_img <- stackObjects(cmask,rgb.imgs)
display(st_img)
